// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCurrentGameState() {
  return window['go']['models']['GameState']['ClearCurrentGameState']();
}

export function GetCurrentGameStateGrid() {
  return window['go']['models']['GameState']['GetCurrentGameStateGrid']();
}

export function KillCell(arg1, arg2) {
  return window['go']['models']['GameState']['KillCell'](arg1, arg2);
}

export function SpawnCell(arg1, arg2) {
  return window['go']['models']['GameState']['SpawnCell'](arg1, arg2);
}

export function UpdateToNextFrame() {
  return window['go']['models']['GameState']['UpdateToNextFrame']();
}
