// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCurrentGameState():Promise<void>;

export function GetCurrentGameStateGrid():Promise<Array<Array<boolean>>>;

export function KillCell(arg1:number,arg2:number):Promise<void>;

export function SpawnCell(arg1:number,arg2:number):Promise<void>;

export function UpdateToNextFrame():Promise<void>;
